@startuml 
    Class "User" as person{
   
        - Int id
        - String name, fname, handle
        - Int age
        - String identity
        - String email
        - String bio
        - Double lon, lat
        - Float perimeter
        - Bool desert
        - Float tauxCuisson 
        - List<CookType> favCookType
        - List<Diet> diets
        - List<User> likedUsers, matchedUsers, dislikedUsers
        - Map<Discussion, List<Message>> discussions

        + void addObjectToList(List<Object> list, User o)
        + void removeObjectFromList(List<Object> list, Object o)
        + List<User> itsCookingTime(List<User> users)
        + void writeMessage(Message m, Discussion d)
        + void leaveDiscussion(Discussion d)
    }

    Class "CookType" as cookType{
        - Int id
        - String name
    }

    Class "Diet" as diet{
        - Int id
        - String name
    }

    Class "Dish" as dish{
        - Int id
        - String name
        - String description
        - String image
        - CookType cookType
        - []Diet diets

        + addDiets(Diet d)
        + removeDiets()

    }

    Class "Restaurant" as restaurant{
        - Int id
        - String name
        - String address
        - CookType cookType
        - List<Dish> dishes

        + addDish(Dish d)
        + removeDish(Dish d)
    }


    /'Class "Message" as messaging{
        - String messages        
        - DateTime timestamp
        - Person sender
        - Discussion discussion
    }

    Class "Discussion" as discuss{
        - []Message messages
        - Person[] participants
        - Observable observable

        + Message addMsg(Message m)
        + Message updateMessages(Message m)
        + void removeMsg(Message m)
    }

    Interface "MessagingSystemObserver" as observer{
        - void update()
    }

    Class "MessagingSystemObservable" as observable{
        - List<User> observers
        - void addObserver(Observer o)
        - void removeObserver(Observer o)
        - void notifyObservers()
    }'/

    person o-- "0..4" cookType
    person o-- "0..*" diet
    person - "0..*" person

    dish o--- "1" cookType
    dish o-- "0..*" diet
    
    /'discuss "1" *-- "0..*" messaging
    messaging "1" -- "1" person
    person "2" *-- "0..*" discuss'/

    restaurant o-- "1" cookType
    restaurant o-- "0..*" dish

    /'discuss "1" *-- "0..*" observable
    observable ..|> observer'/

@enduml