@startuml 
    Class "User" as person{
   
        - Int id
        - String name
        - String surname
        - Int age
        - String identity
        - String email
        - String bio
        - Double lon
        - Double lat
        - Float perimeter
        - Bool desert
        - Float tauxCuisson 
        - []Person liked
        - []Person matched
        - []CookType favCookType
        - []Diet diets
        - []User likedUsers
        - []User matchedUsers
        - []User dislikedUsers
        - []User matchingCandidates

        + void addObjectToList(List<Object> list, User o)
        + void removeObjectFromList(List<Object> list, Object o)
        + []User itsCookingTime([]User users)

    }

    Class "CookType" as cookType{
        - Int id
        - String name
    }

    Class "Diet" as diet{
        - Int id
        - String name
    }

    Class "Dish" as dish{
        - Int id
        - String name
        - String description
        - String image
        - CookType cookType
        - []Diet diets

        + addDiets(Diet d)
        + removeDiets()
    }

    person "0..*" o-- "0..*" cookType
    person "0..*" o-- "0..*" diet

    dish "1" *--- "0..*" cookType
    dish "0..*" *-- "0..*" diet
    person "0..*" o- "0..*" person
@enduml