@startuml 
    Class "User" as person{
   
        - Int id
        - String name
        - String surname
        - Int age
        - String identity
        - String email
        - String bio
        - Double lon
        - Double lat
        - Float perimeter
        - Bool desert
        - Float tauxCuisson 
        - []Person liked
        - []Person matched
        - []CookType favCookType
        - []Diet diets
        - []User likedUsers
        - []User matchedUsers
        - []User dislikedUsers
        - []User matchingCandidates

        + void addObjectToList(List<Object> list, User o)
        + void removeObjectFromList(List<Object> list, Object o)
        + []User itsCookingTime([]User users)

    }


    Class "Message" as messaging{
        - String messages        
        - DateTime timestamp
        - Person sender
        - Discussion discussion
    }

    Class "Discussion" as discuss{
        - []Message messages
        - Person[] participants
    }

    discuss "1" -- "0..*" messaging
    messaging "1" -- "1" person
    person "2" -- "0..*" discuss